language: python

python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3

env:
    - DJANGO=1.4.10
    - DJANGO=1.5.5
    - DJANGO=1.6.1
    - DJANGO=1.7

matrix:
    exclude:
        - python: 2.6
          env: DJANGO=1.7
        - python: 3.2
          env: DJANGO=1.4.10
        - python: 3.3
          env: DJANGO=1.4.10

install:
    - pip install -q coveralls django==$DJANGO --use-mirrors
    - pip install flake8

before_script:
    - flake8 preserialize

script:
    - coverage run test_suite.py

after_success:
    - coveralls
