language: python
python:
    - "2.6"
    - "2.7"
env:
    - DJANGO=1.4.5
    - DJANGO=1.5.1
install:
    - pip install coveralls
    - pip install -q Django==$DJANGO --use-mirrors
script:
    - coverage run --source=preserialize setup.py test
after_success:
    - coveralls
